Repository UofT-Frosh-Orientation/orientation-website, pull requests merged in 2023-07, with the labels that each got.

#668 fixed useEffect async functions
  client/src/components/Navbar/Navbar.jsx
  client/src/pages/FAQ/FAQ.jsx
  client/src/pages/FroshRetreat/FroshRetreat.jsx
  client/src/pages/Home/Home.jsx
  client/src/pages/Profile/Profile.jsx
  client/src/pages/ScuntGameSettings/ScuntGameSettings.jsx
  client/src/util/pages.jsx
Labels: bug, front-end

#670 Update DOM render and fix Navbar warning
  client/src/components/Navbar/Navbar.jsx
  client/src/main.jsx
Labels: bug, front-end

#672 648 update QR code logic
  client/src/components/MakeReceipt/MakeReceipt.jsx
  client/src/pages/Profile/Profile.jsx
  client/src/pages/Profile/functions.jsx
  server/.eslintrc.js
  server/src/controllers/FaqController.js
  server/src/controllers/FroshController.js
  server/src/controllers/QrController.js
  server/src/controllers/UserController.js
  server/src/services/UserServices.js
Labels: Infrastructure, full-stack

#655 653 update registration fields & 664 schedule update
  client/src/assets/schedule/data.jsx
  client/src/components/MakeReceipt/MakeReceipt.jsx
  client/src/components/input/TextInput/TextInput.jsx
  client/src/components/schedule/ScheduleHome/ScheduleHome.jsx
  client/src/pages/FroshRetreat/FroshRetreat.jsx
  client/src/pages/Home/Home.jsx
  client/src/pages/Profile/Profile.scss
  client/src/pages/Profile/functions.jsx
  client/src/pages/ProfileEdit/ProfileEdit.jsx
  client/src/pages/ProfileEdit/ProfileEdit.scss
  client/src/pages/Registration/OldRegistrationFields.jsx
  client/src/pages/Registration/RegistrationFields.jsx
  client/src/pages/Registration/RegistrationForm.jsx
  client/src/pages/ScuntHome/ScuntHome.jsx
  server/src/controllers/FroshController.js
  server/src/controllers/UserController.js
  server/src/models/FroshModel.js
Labels: enhancement, front-end

#689 55 set up automated testing on GitHub
  .github/workflows/automated_tests.yml
  docker-compose.test.yml
  package.json
  server/.gitignore
  server/package.json
  server/src/tests/db.js
  server/src/tests/frosh.test.js
  server/test/dbconfig.test.js
  server/test/routers/announcementRoutes.test.js
  server/test/routers/faqRoutes.test.js
  server/test/routers/froshRoutes.test.js
  server/test/routers/paymentRoutes.test.js
  server/test/routers/qrRoutes.test.js
  server/test/routers/scuntGameSettingsRoutes.test.js
  server/test/routers/scuntMissionRoutes.test.js
  server/test/routers/scuntRoutes.test.js
  server/test/routers/scuntTeamRoutes.test.js
  server/test/routers/timelineRoutes.test.js
  server/test/routers/userRoutes.test.js
  server/test/services/AnnouncementServices.test.js
  server/test/services/EmailServices.test.js
  server/test/services/FaqServices.test.js
  server/test/services/FroshServices.test.js
  server/test/services/LeadurServices.test.js
  server/test/services/PaymentServices.test.js
  server/test/services/ScuntGameSettingsServices.test.js
  server/test/services/ScuntMissionServices.test.js
  server/test/services/ScuntTeamServices.test.js
  server/test/services/TimelineServices.test.js
  server/test/services/UserServices.test.js
  server/test/services/passport.test.js
  server/yarn.lock
Labels: back-end, Infrastructure
