Repository UofT-Frosh-Orientation/orientation-website, pull requests merged in 2023-06, with the labels that each got.

#615 611 set up nginx on server
  .github/workflows/beta_deployment.yml
  docker-compose.yml
  docs/.dockerignore
  docs/.gitignore
  docs/Dockerfile
  docs/Gemfile.lock
  docs/pages/Onboarding/Hosting.md
Labels: documentation, enhancement, back-end

#613 About Us Page Optimizations
  client/src/pages/About/About.jsx
  client/src/pages/About/About.scss
  client/src/pages/About/ExecProfile/ExecProfile.jsx
Labels: front-end

#616 Duplicated changes for header modification
  client/src/assets/logo/frosh-hard-hat-white.svg
  client/src/pages/Home/Home.jsx
  client/src/pages/Home/Home.scss
  client/src/pages/Home/functions.jsx
Labels: front-end

#625 602 Dynamically changing class year
  client/src/pages/Profile/Profile.jsx
Labels: front-end

#639 fixed navbar spacing and removed extra comments
  client/src/App.jsx
  client/src/App.scss
  client/src/pages/FAQ/FAQ.jsx
  client/src/pages/FroshInfoTable/FroshInfoTable.jsx
  client/src/pages/Profile/Profile.jsx
  client/src/pages/ProfileEdit/ProfileEdit.jsx
  client/src/pages/Registration/RegistrationForm.jsx
  client/src/pages/RegistrationSuccess/RegistrationSuccess.jsx
  client/src/pages/ScopeRequest/ScopeRequest.jsx
  client/src/pages/ScuntJudgeForm/ScuntJudgeForm.jsx
  client/src/pages/SignUp/SignUp.jsx
Labels: enhancement, front-end

#632 adding period as special character
  client/src/pages/SignUp/SignUp.jsx
  client/src/pages/SignUp/functions.jsx
  server/src/services/UserServices.js
Labels: front-end, Infrastructure

#617 603 organize leedur profile dashboard
  client/src/assets/dashboarddropdown/data-icon.svg
  client/src/assets/dashboarddropdown/outreach-icon.svg
  client/src/assets/dashboarddropdown/scunt-icon.svg
  client/src/components/DashboardDropdown/DashboardDropdown.jsx
  client/src/components/DashboardDropdown/DashboardDropdown.scss
  client/src/pages/Profile/Profile.jsx
  client/src/pages/Profile/Profile.scss
Labels: enhancement, front-end

#631 353 edit profile page for non registered users v2
  client/src/pages/Profile/Profile.jsx
  client/src/pages/ProfileEdit/ProfileEdit.jsx
  client/src/pages/ProfileEdit/ProfileEdit.scss
  client/src/pages/ProfileEditUnregistered/ProfileEditUnregistered.jsx
  client/src/pages/ProfileEditUnregistered/ProfileEditUnregistered.scss
  client/src/state/user/saga.jsx
  client/src/util/pages.jsx
  server/src/controllers/UserController.js
  server/src/routes/userRoutes.js
Labels: enhancement, full-stack
